export { default as profile } from './profile/reducer'
export { default as loading } from './loading/reducer'
export { default as admin } from './admin/reducer'
export { default as articles } from './articles/reducer'
export { default as screen } from './screen/reducer'
